### ISSUE TITLE
package org.apache.xerces.impl.dv.util does not exist

### ISSUE THREAD

**Issue by mrgroen** [ArjenLammers/sftp-connector#1]
The "xerces.xercesImpl.2.8.1.jar" seems to be removed from the community commons module. Therefore the project cannot compile if it is missing.
What dependency should i use to keep it future proof?

**Comment by ArjenLammers** [comment]
Hi Marcus,

You can use release 1.1.
The dependency on Xerces has been removed.

Kind regards

**Comment by mrgroen** [comment]
Thanks! Nice job.
