### ISSUE TITLE
Vulnerability in jar file: commons-codec:commons-codec

### ISSUE THREAD

**Issue by mwbouwkamp-mendix** [ArjenLammers/sftp-connector#13]
The following jar file has a vulnerability: commons-codec:commons-codec

Introduced through: commons-codec:commons-codec@1.10
Fixed in: commons-codec:commons-codec@1.13

**Comment by ArjenLammers** [comment]
HI @mwbouwkamp-mendix , this should be fixed in the version 2.5 which has been published in the Marketplace.

Kind regards,
Arjen Lammers
